# Dependencies
gems: [jekyll-paginate]

markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            1447 South Clark Street
tagline:          'A Jekyll theme'
description:      'Chicago, IL 60605 <br>
                   Agent: <a href="http://www.remax-ni.net/realestatehomesforsale/1447-south-clark-street-chicago-near-south-side-il-60605-gid600013805666.html">Cynthia  Bauer</a>'
#url:              http://1447clark.mchaler.org
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rmchale/1447clark
